#!/bin/bash

case "$1" in
    remove|purge)
        for f in cstbox cstbox-avahi-* cstbox-cfgbroker cstbox-cron cstbox-dbus cstbox-evtmgr; do
            rm -f /etc/init.d/$f
        done
        rm -rf /etc/cron.d/cstbox

        if [ "$1" = "purge" ] ; then
            rm -rf /etc/cstbox /var/log/cstbox /var/db/cstbox
        fi
        ;;
esac

