#!/bin/bash

#set -e

. /etc/cstbox/setenv
. $CSTBOX_LIB_DPKG/lib-maintscript

# stop running CSTBox services, if any 

service cstbox stop

# unregister CSTBox services from init process

echo "Removing CSTBox services from system startup..."
update-rc.d -f cstbox remove > /dev/null

cleanup_pyc
