#! /bin/bash
### BEGIN INIT INFO
# Provides:          cstbox-cron
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CSTBox scheduled tasks (de)activation
# Description:       This service must be started once 
#                    the CSTBox framework is ready.
### END INIT INFO

# This file is part of CSTBox.
#
# CSTBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CSTBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with CSTBox.  If not, see <http://www.gnu.org/licenses/>.

# Author: Eric Pascual <eric.pascual@cstb.fr>

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="CSTBox scheduled tasks activation"
NAME=cstbox-cron
INIT_SEQ=95
CORE_SVC=1

# the CSTBox crontab is stored with all the other CSTBox configuration files
CSTBOX_CRONTAB="/etc/cstbox/crontab"
# per package crontab (will be a symlink to real file above)
CRONTABS_HOME="/etc/cron.d"
CRON_D_CONFIG="$CRONTABS_HOME/cstbox"

INIT_VERBOSE=yes

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

case "$1" in
  start)
        if [ -e $CRON_D_CONFIG ] ; then
            log_daemon_msg "Already started"
            log_end_msg 2
        else
            # create cron configuration directory in case not here
            [ -e $CRONTABS_HOME ] || mkdir -p $CRONTABS_HOME
            ln -s $CSTBOX_CRONTAB $CRON_D_CONFIG
            [ "$VERBOSE" != no ] && log_daemon_msg "Starting $NAME ($DESC)"
            if [ $? -eq 0 ] ; then
                [ "$VERBOSE" != no ] && log_end_msg 0 
            else 
                [ "$VERBOSE" != no ] && log_end_msg 1 
            fi
        fi
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $NAME ($DESC)"
        rm -f $CRON_D_CONFIG
        if [ $? -eq 0 ] ; then
	    [ "$VERBOSE" != no ] && log_end_msg 0 
        else 
	    [ "$VERBOSE" != no ] && log_end_msg 1 
        fi
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop}" >&2
	exit 3
	;;
esac

